ANPositive/Models/Shared/Result.cs
namespace ANPositive.Models.Shared
{
    public class Result
    {
        public bool success { get; set; }
        public string title { get; set; }
        public string message { get; set; }
    }
}

ANPositive/Models/Shared/autoComplete.cs
namespace ANPositive.Models.Shared
{
    public class AutoComplete
    {
        public string value { get; set; }
    }
}

ANPositive/Models/Shared/displayOrder.cs
namespace ANPositive.Models
{
    public class displayOrders
    {
        public int id { get; set; }
        public int displayOrder { get; set; }
    }
}

ANPositive/Models/Shared/filesViewModel.cs
namespace ANPositive
{
    public class FilesViewModel
    {
        public ViewDataUploadFilesResult[] Files { get; set; }
    }
}

ANPositive/Models/Shared/uploadedFile.cs
using System.Collections.Generic;
using System.Linq;

namespace ANPositive.Models
{
    public class ViewDataUploadFilesResult
    {
        public string name { get; set; }
        public int size { get; set; }
        public string type { get; set; }
        public string url { get; set; }
        public string deleteUrl { get; set; }
        public string thumbnailUrl { get; set; }
        public string deleteType { get; set; }
    }

    public class JsonFiles
    {
        public ViewDataUploadFilesResult[] files;
        public string TempFolder { get; set; }
        public JsonFiles(List<ViewDataUploadFilesResult> filesList)
        {
            files = new ViewDataUploadFilesResult[filesList.Count];
            for (int i = 0; i < filesList.Count; i++)
            {
                files[i] = filesList.ElementAt(i);
            }

        }
    }
}

ANPositive/Areas/Admin/Controllers/Application/FileUploadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Hosting;
using System.Web.Mvc;

namespace ANPositive.Areas.Admin.Controllers
{
    public class FileUploadController : Controller
    {
        FilesHelper filesHelper;
        String tempPath = "~/uploads/";
        String serverMapPath = "~/uploads/";

        private string StorageRoot
        {
            get { return Path.Combine(HostingEnvironment.MapPath(serverMapPath)); }
        }

        private string UrlBase = "/uploads/";

        String DeleteURL = "/Admin/FileUpload/DeleteFile/?file=";
        String DeleteType = "GET";

        public FileUploadController()
        {
            filesHelper = new FilesHelper(DeleteURL, DeleteType, StorageRoot, UrlBase, tempPath, serverMapPath);
        }

        public ActionResult Show()
        {
            string subFolder = Request.QueryString["subFolder"] != null ? HttpContext.Request.QueryString["subFolder"].ToString() : "user-files";
            JsonFiles ListOfFiles = filesHelper.GetFileList(subFolder);
            var model = new FilesViewModel()
            {
                Files = ListOfFiles.files
            };

            return View(model);
        }

        [HttpPost]
        public JsonResult Upload()
        {
            var resultList = new List<ViewDataUploadFilesResult>();
            var CurrentContext = HttpContext;
            string subFolder = Request.QueryString["subFolder"] != null ? CurrentContext.Request.QueryString["subFolder"].ToString() : "user-files";

            filesHelper.UploadAndShowResults(CurrentContext, resultList, subFolder);

            JsonFiles files = new JsonFiles(resultList);

            bool isEmpty = !resultList.Any();
            if (isEmpty)
            {
                return Json("Error ");
            }
            else
            {
                return Json(files);
            }
        }

        public JsonResult GetFileList()
        {
            string subFolder = Request.QueryString["subFolder"] != null ? HttpContext.Request.QueryString["subFolder"].ToString() : "user-files";
            var list=filesHelper.GetFileList(subFolder);
            return Json(list,JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult DeleteFile(string file, string subFolder)
        {
            filesHelper.DeleteFile(file, subFolder);
            return Json("OK", JsonRequestBehavior.AllowGet);
        }
    }
}

ANPositive/Controllers/Shared/PartialController.cs
using ANPositive.Models;
using Microsoft.AspNet.Identity.Owin;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ANPositive.Controllers
{
    public class PartialController : Controller
    {
        /// <summary>
        /// Context
        /// </summary>
        private ApplicationDbContext _dbContext;

        public ApplicationDbContext DbContext
        {
            get
            {
                return _dbContext ?? HttpContext.GetOwinContext().Get<ApplicationDbContext>();
            }
            private set
            {
                _dbContext = value;
            }

        }

        public PartialController()
        {

        }

        public PartialController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public ActionResult NavigationMenu(int menuPosition, int lang)
        {
            List<Content> contents = DbContext.contents.Where(item => item.published && !item.isDeleted && item.language == lang && item.menuPosition == menuPosition).OrderBy(item => item.displayOrder).ToList();

            return PartialView("~/Views/Shared/_Navigation.cshtml", contents);
        }
    }
}

ANPositive/Areas/Admin/Views/Shared/_BreadCrumb.cshtml
@using System.Configuration;

@model string

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-6 col-xs-12">
        <h2>@ViewBag.Title</h2>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index", "Dashboard")">@ConfigurationManager.AppSettings["applicationName"]</a></li>
            @{
                if (ViewBag.TopMenu != null)
                {
            <li><a href="@Url.Action("Index", HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString())"> @ViewBag.TopMenu</a></li>
                }
            }
            <li class="active"><strong>@ViewBag.Title</strong></li>
        </ol>
    </div>
    <div class="col-sm-6 col-xs-12 text-right actionButtonArea @(Model == string.Empty ? "hide": null)">
        <a href="@Url.Action(HttpContext.Current.Request.RequestContext.RouteData.Values["action"].ToString().ToLower() == "list" ? "Insert" : "List", HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString())" class="btn btn-success">
            @{ 
                if (HttpContext.Current.Request.RequestContext.RouteData.Values["action"].ToString().ToLower() == "list")
                {
                    <i class="fa fa-plus-square"></i>
                }else
                {
                    <i class="fa fa-chevron-left"></i>
                }
            }
            &nbsp;&nbsp;@Model
        </a>
    </div>
</div>

ANPositive/Areas/Admin/Views/Shared/_Footer.cshtml
@using System.Configuration;

<input type="hidden" id="primaryKey" />
<input type="hidden" id="iladi" />

<div class="footer">
    <div class="pull-right">
        <strong>Version</strong> @ConfigurationManager.AppSettings["applicationVersion"]
    </div>
    <div>
        <strong>Copyright</strong> &copy; 2009-@DateTime.Now.Year.ToString() <a href="https://ajansnaber.com" target="_blank">AN+ Creative Solutions</a>. Tüm Hakları Saklıdır.
    </div>
</div>

<script type="text/javascript">
    var appName = "@ConfigurationManager.AppSettings["applicationName"]";
</script>

ANPositive/Areas/Admin/Views/Shared/_Layout.cshtml
@{
    BundleTable.EnableOptimizations = false;
}

<!DOCTYPE html>
<html lang="tr">
<head>
    <title>@ViewBag.Title | ANPositive Creative Solutions</title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <link rel="shortcut icon" href="/images/favicon/favicon.ico" type="image/x-icon" />
    <link rel="apple-touch-icon" href="/images/favicon/apple-touch-icon.png" />
    <link rel="apple-touch-icon" sizes="57x57" href="/images/favicon/apple-touch-icon-57x57.png" />
    <link rel="apple-touch-icon" sizes="72x72" href="/images/favicon/apple-touch-icon-72x72.png" />
    <link rel="apple-touch-icon" sizes="76x76" href="/images/favicon/apple-touch-icon-76x76.png" />
    <link rel="apple-touch-icon" sizes="114x114" href="/images/favicon/apple-touch-icon-114x114.png" />
    <link rel="apple-touch-icon" sizes="120x120" href="/images/favicon/apple-touch-icon-120x120.png" />
    <link rel="apple-touch-icon" sizes="144x144" href="/images/favicon/apple-touch-icon-144x144.png" />
    <link rel="apple-touch-icon" sizes="152x152" href="/images/favicon/apple-touch-icon-152x152.png" />
    <link rel="apple-touch-icon" sizes="180x180" href="/images/favicon/apple-touch-icon-180x180.png" />

    @Styles.Render("~/Scripts/plugins/jquery-ui/jqueryuiStyles")
    @Styles.Render("~/font-awesome/css")
    @Styles.Render("~/Content/css")

    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}
</head>
<body>
    <div id="wrapper" class="@Html.PageClass()">
        @Html.Partial("_Navigation")
        <div id="page-wrapper" class="gray-bg @ViewBag.SpecialClass">
            @Html.Partial("_TopNavbar")
            @RenderBody()
            @Html.Partial("_Footer")
        </div>
    </div>

    @Html.Raw(JSNLog.JavascriptLogging.Configure())
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/plugins/slimScroll")
    @Scripts.Render("~/bundles/inspinia")

    @RenderSection("scripts", required: false)
</body>
</html>

ANPositive/Areas/Admin/Views/Shared/_MultiFileUpload.cshtml
@model string
<form id="fileupload" method="POST" enctype="multipart/form-data" data-url="@Url.Action("Upload", "FileUpload", new { subFolder = Model.ToString() })">
    <div class="row fileupload-buttonbar">
        <div class="col-lg-7">
            <span class="btn btn-success fileinput-button">
                <i class="glyphicon glyphicon-plus"></i>
                <span>Görsel Ekle...</span>
                <input type="file" name="files[]" accept="image/*" multiple>
            </span>
            <button type="submit" class="btn btn-primary start">
                <i class="glyphicon glyphicon-upload"></i>
                <span>Yüklemeye Başla</span>
            </button>
            <button type="reset" class="btn btn-warning cancel">
                <i class="glyphicon glyphicon-ban-circle"></i>
                <span>Vazgeç</span>
            </button>
            <button type="button" class="btn btn-danger delete">
                <i class="glyphicon glyphicon-trash"></i>
                <span>Sil</span>
            </button>
            <input type="checkbox" class="toggle">
            <span class="fileupload-process"></span>
        </div>
        <div class="col-lg-5 fileupload-progress fade">
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                <div class="progress-bar progress-bar-success" style="width: 0%;"></div>
            </div>
            <div class="progress-extended">&nbsp;</div>
        </div>
    </div>
    <div class="col-lg-5 fileupload-progress fade">
        <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
            <div class="progress-bar progress-bar-success" style="width: 0%;"></div>
        </div>
        <div class="progress-extended">&nbsp;</div>
    </div>
    <table role="presentation" class="table table-striped">
        <tbody class="files"></tbody>
    </table>
</form>
<br />
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-filter=":even">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>
<script id="template-upload" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
        <td>
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger"></strong>
        </td>
        <td>
            <p class="size">Processing...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td>
            {% if (!i && !o.options.autoUpload) { %}
            <button class="btn btn-primary start" disabled>
                <i class="glyphicon glyphicon-upload"></i>
                <span>Yüklemeye Başla</span>
            </button>
            {% } %}
            {% if (!i) { %}
            <button class="btn btn-warning cancel">
                <i class="glyphicon glyphicon-ban-circle"></i>
                <span>Vazgeç</span>
            </button>
            {% } %}
        </td>
    </tr>
    {% } %}
</script>
<script id="template-download" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        <td>
            <span class="preview">
                {% if (file.thumbnailUrl) { %}
                <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnailUrl%}" style="height:40px;"></a>
                {% } %}
            </span>
        </td>
        <td>
            <p class="name">
                {% if (file.url) { %}
                <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                {% } else { %}
                <span>{%=file.name%}</span>
                {% } %}
            </p>
            {% if (file.error) { %}
            <div><span class="label label-danger">Error</span> {%=file.error%}</div>
            {% } %}
        </td>
        <td>
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>
        <td>
            {% if (file.deleteUrl) { %}
            <button class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}" {% if (file.deletewithcredentials) { %} data-xhr-fields='{"withCredentials":true}' {% } %}>
                <i class="glyphicon glyphicon-trash"></i>
                <span>Sil</span>
            </button>
            <input type="checkbox" name="delete" value="1" class="toggle">
            {% } else { %}
            <button class="btn btn-warning cancel">
                <i class="glyphicon glyphicon-ban-circle"></i>
                <span>Vazgeç</span>
            </button>
            {% } %}
        </td>
    </tr>
    {% } %}
</script>

ANPositive/Areas/Admin/Views/Shared/_Navigation.cshtml
@using ANPositive.Models
@using Microsoft.AspNet.Identity
@using Microsoft.AspNet.Identity.Owin

@{
    ApplicationUser user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());
}
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element text-center">
                    <span>
                        <img src="~/images/Admin/avatar.png" class="img-circle" alt="@user.firstName @user.lastName" />
                    </span>
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear">
                            <span class="block m-t-xs">
                                <strong class="font-bold">@user.firstName @user.lastName</strong>
                            </span> <span class="text-muted text-xs block">@user.title <b class="caret"></b></span>
                        </span>
                    </a>
                    @using (Html.BeginForm("LogOff", "Account", new { area = "" }, FormMethod.Post, new { id = "logoutForm", @class = "m-t" }))
                    {
                        @Html.AntiForgeryToken()
                    }
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="@Url.Action("Index", "Manage")">Profil</a></li>
                        <li class="divider"></li>
                        <li><a href="javascript:document.getElementById('logoutForm').submit()">Çıkış</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    AN+
                </div>
            </li>

            <li class="@Html.IsSelected(controller: "Content")">
                <a href="@Url.Action("Index", "Content")">
                    <i class="fa fa-file-text-o"></i>
                    <span class="nav-label">İçerik Yönetimi</span>
                </a>
            </li>

            <li class="@Html.IsSelected(controller: "Gallery")">
                <a href="@Url.Action("Index", "Gallery")">
                    <i class="fa fa-picture-o"></i>
                    <span class="nav-label">Galeri Yönetimi</span>
                </a>
            </li>
            
            @{
                if (User.IsInRole(RoleNames.roleAdministrator))
                {
                    <li class="@Html.IsSelected(controller: "User")">
                        <a href="@Url.Action("Index", "User")">
                            <i class="fa fa-users"></i>
                            <span class="nav-label">Kullanıcılar</span>
                        </a>
                    </li>
                }
            }

            <li>
                <a href="@Url.Action(((Route)Url.RouteCollection["Default"]).Defaults["action"].ToString(), ((Route)Url.RouteCollection["Default"]).Defaults["controller"].ToString(), new { area = "" }, null)" target="_blank">
                    <i class="fa fa-globe"></i>
                    <span class="nav-label">Siteye Git</span>
                </a>
            </li>
        </ul>
    </div>
</nav>

ANPositive/Areas/Admin/Views/Shared/_SingleFileUpload.cshtml
<div class="form-group col-md-4 uploadFile">
    <span class="btn btn-success fileinput-button btn-block">
        <i class="glyphicon glyphicon-plus"></i>
        <span>Görsel Yükle...</span>
        <input id="fileupload" type="file" name="files[]" data-url="@Url.Action("Upload", "FileUpload", new { subFolder = Model.ToString() })" />
    </span>
</div>
<div class="form-group col-md-8 uploadFile">
    <div id="progress" class="progress">
        <div class="progress-bar progress-bar-success"></div>
    </div>
</div>
<div class="form-group col-md-6 fileIsUploaded hide" style="padding-top: 10px;">
    <i class="fa fa-exchange"></i><a href="javascript:;" onclick="application.listImages.resetImages();">Görseli Değiştir</a>
</div>
<div class="form-group col-md-6 fileIsUploaded showUploadedFile hide" style="padding-top: 6px;"></div>

ANPositive/Areas/Admin/Views/Shared/_TopNavbar.cshtml
@using System.Configuration;

<div class="row border-bottom">
    <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li>
                <span class="m-r-sm text-muted welcome-message" data-i18n="topnav.welcometext">@ConfigurationManager.AppSettings["applicationName"] Yönetim Paneli</span>
            </li>
            <li>
                <a href="javascript:document.getElementById('logoutForm').submit()">
                    <i class="fa fa-sign-out"></i> Çıkış Yap
                </a>
            </li>
        </ul>
    </nav>
</div>